#Autostartx for start dwm window manger in tty2 by defult
[[ ! $DISPLAY && $(tty) = "/dev/tty2" ]] && startx




# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi


# Created by Zap installer
[ -f "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh" ] && source "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh"
plug "zsh-users/zsh-autosuggestions"
plug "zsh-users/zsh-history-substring-search"
plug "romkatv/powerlevel10k"
plug "zdharma/fast-syntax-highlighting"
plug "zap-zsh/fzf" # helper plugin to fzf ctrl + r , ctrl + t , alt + c  
plug "zap-zsh/completions"
plug "KulkarniKaustubh/fzf-dir-navigator"
# Enable fzf's tab completion and key bindings
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
eval "$(fzf --zsh)"

#fzf use fd 
export FZF_DEFAULT_COMMAND="fd --strip-cwd-prefix --exclude .git"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND="fd --type=d --strip-cwd-prefix --exclude .git"
# Function to generate the list of path candidates for completion (excluding hidden files)
_fzf_compgen_path() {
  fd --exclude .git . "$1"
}
# Function to generate the list for directory completion (excluding hidden files)
_fzf_compgen_dir() {
  fd --type=d --exclude .git . "$1"
}

#####fzf better use 
export FZF_CTRL_T_OPTS="--preview 'bat -n --color=always --line-range :500 {}'"
export FZF_ALT_C_OPTS="--preview 'eza --tree --color=always {} | head -200'"

# Advanced customization of fzf options via _fzf_comprun function
# - The first argument to the function is the name of the command.
# - You should make sure to pass the rest of the arguments to fzf.
_fzf_comprun() {
  local command=$1
  shift

  case "$command" in
    cd)           fzf --preview 'eza --tree --color=always {} | head -200' "$@" ;;
    export|unset) fzf --preview "eval 'echo $'{}"         "$@" ;;
    ssh)          fzf --preview 'dig {}'                   "$@" ;;
    *)            fzf --preview "bat -n --color=always --line-range :500 {}" "$@" ;;
  esac
}
# nnn jump commaned
eval "$(jump shell zsh)"

# cd smart
eval "$(zoxide init zsh)"

#key bindings his-sub-search wiht fzf wiht the arrow buttoun  
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
# change directory just by typing its name 
setopt autocd 


# Load and initialise completion system
autoload -Uz compinit
compinit


## xbps
alias i='doas xbps-install -S '
alias u='doas xbps-install -S; doas xbps-install -u xbps; doas xbps-install -u'
alias q='doas xbps-query -Rs'
alias r='sudo xbps-remove -R'

# History configurations
HISTFILE=~/.zsh_history
HISTSIZE=100000000000000
SAVEHIST=200000000000000
HISTDUP=erase
setopt hist_verify            # show command with history expansion to user before running it
setopt share_history         # share command history datasetopt
setopt appendhistory
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups
   


# alias 

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias diff='diff --color=auto'

# Create alias override commands using 'lsd'
alias ls='lsd --group-directories-first'
alias ll='lsd -l --group-directories-first'
alias la='lsd -la --group-directories-first'
alias l='eza --color=always --long --git --no-filesize --icons=always --no-time --no-user --no-permissions'
alias tree='lsd -l --group-directories-first --tree --depth=2'

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh


# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
export TERMINAL=st
export BROWSER=brave-browser-stable

# Function to source nnn.zsh
source ~/.config/nnn/plugins/nnn.zsh
alias nnn='nnn -aRroi'

#######autosuggestion
ZSH_AUTOSUGGEST_STRATEGY=(history completion)
bindkey '^ ' autosuggest-accept


# fnm
export PATH="/home/ronin/.local/share/fnm:$PATH"
eval "`fnm env`"

##Rust
export PATH="$PATH:$HOME/.cargo/bin"

export PATH="$PATH:$HOME/.local/bin"
#flutter  
export PATH="$PATH:/home/ronin/VoidBuild/flutter/bin"
export PATH="$PATH:/home/ronin/VoidBuild/flutter/bin/cache/dart-sdk/bin"

# Function to check parent process and execute bicon.bin if necessary
#    if ! [[ "$(ps -p $(ps -p $(echo $$) -o ppid=) -o comm=)" =~ 'bicon'* ]]; then
#       bicon.bin
# fi
# ----- Bat (better cat) -----

export BAT_THEME=tokyonight_night
#### the fuck 
# thefuck alias
eval $(thefuck --alias)
eval $(thefuck --alias fk)

source /home/ronin/.config/broot/launcher/bash/br
